dbt_bgcflow:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dbt_bgcflow.duckdb'
      threads: 2
      extensions:
        - parquet
      external_root: "../data_warehouse"
    prod:
      dbname: bgcflow
      schema: public
      type: postgres
      threads: 2
      host: localhost
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      extensions:
        - parquet
      external_root: "../data_warehouse"
