dbt_bgcflow:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dbt_bgcflow.duckdb'
      threads: 2
      extensions:
        - parquet
      external_root: "../data_warehouse"
    prod:
      dbname: dbt_bgcflow
      type: postgres
      threads: 2
      host: localhost
      port: 5432
      user: <user id>
      pass: <password>
      extensions:
        - parquet
      external_root: "../data_warehouse"
