name: Platform Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
      name: Validate Getting Started works on linux
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: "3.8.x"
        - name: Full Deploy Commands
          run: |
            python3 -m venv venv
            source venv/bin/activate
            venv/bin/python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
            source venv/bin/activate
            which dbt
            dbt --version
            dbt debug
            #dbt build
            #dbt docs generate
            #duckcli jaffle_shop.duckdb -e "select * from customers where customer_id = 42"
          shell: bash
