name: Platform Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-venv:
      name: Validate on linux using python venv
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: "3.8.x"
        - name: Install venv
          run: |
            python3 -m venv venv
            source venv/bin/activate
            venv/bin/python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
        - name: Build DuckDB
          run: |
            source venv/bin/activate
            python scripts/source_template.py templates/_sources.yml models/sources.yml "6.1.1" "0.30"
            which dbt
            dbt --version
            dbt debug
            #dbt build
            #dbt docs generate
          shell: bash
